### ISSUE TITLE
Build error on Windows x64

### ISSUE THREAD

**Issue by jack980517** [naftaliharris/tauthon#132]
```
Traceback (most recent call last):
  File "./setup.py", line 2356, in <module>
    main()
  File "./setup.py", line 2351, in main
    'Lib/smtpd.py']
  File "/d/tauthon-master/Lib/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/d/tauthon-master/Lib/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/d/tauthon-master/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/d/tauthon-master/Lib/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/d/tauthon-master/Lib/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/d/tauthon-master/Lib/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/d/tauthon-master/Lib/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "./setup.py", line 315, in build_extensions
    build_ext.build_extensions(self)
  File "/d/tauthon-master/Lib/distutils/command/build_ext.py", line 449, in build_extensions
    self.build_extension(ext)
  File "./setup.py", line 351, in build_extension
    if not self.configure_ctypes(ext):
  File "./setup.py", line 2106, in configure_ctypes
    exec f in fficonfig
  File "build/temp.mingw64_nt-10.0-10240-3.0.7-338.x86_64-x86_64-2.8/libffi/fficonfig.py", line 33, in <module>
    ffi_sources += ffi_platforms['X86_WIN64']
KeyError: 'X86_WIN64'
make: *** [Makefile:540: sharedmods] Error 1
```
Using commit a777ae6 and msys2 64bit

**Comment by jack980517** [comment]
nvm, figured out i should use visual studio instead
