### ISSUE TITLE
Get homebrew packages for tauthon

### ISSUE THREAD

**Issue by naftaliharris** [naftaliharris/tauthon#70]

**Comment by torgil** [comment]
Is anyone working on this?

Trying just to do "python setup.py build"  from homebrew and run the produced "python.exe" has a number of missing build-dependencies (I run Sierra 10.12.3) :

```
$ python --version
Python 2.7.13
$ which python
/usr/local/bin/python
$ ls -l /usr/local/bin/python
/usr/local/bin/python -> ../Cellar/python/2.7.13/bin/python
$ git rev-parse HEAD
8e4dc294920bad1cd54cac8f8e1bd9d26d38d8ed

```
**Issue1:** link-error for 'cmath' and 'math' extenstions
`
clang: error: no such file or directory: 'Modules/_math.o'
`
I fixed this with just building the offending object manually:
`
clang -fno-strict-aliasing -fno-common -dynamic -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I./Mac/Include -I. -IInclude -I./Include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c ./Modules/_math.c -o ./Modules/_math.o
`
**Issue2:** missing symbol in operator.so  _PyNumber_InPlaceMatrixMultiply
Here I found that the missing symbol was defined in Objects/abstracts.c so I just linked manually with that object:
`
clang -bundle -undefined dynamic_lookup ./Modules/operator.o ./Objects/abstract.o -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -o build/lib.macosx-10.12-x86_64-2.7/operator.so
`
**Issue 3:** runtime error directly when starting python

`
$ ./python.exe
...
ImportError: No module named _sysconfigdata
`

I didn't fix this I just did this workaround:

`
$ cp /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_sysconfigdata.py Lib/
`

**Issue4:** 

`
>>> import functools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/torgil/src/python/tauthon/Lib/functools.py", line 10, in <module>
    from _functools import partial, reduce
ImportError: No module named _functools
`
I stopped here, I guess a workaround for this isn't as easy as copying from Python2.7..

**Comment by naftaliharris** [comment]
> Is anyone working on this?

No, but I'd love help on it! :-)

> Trying just to do "python setup.py build" from homebrew and run the produced "python.exe" has a number of missing build-dependencies (I run Sierra 10.12.3) :

I believe you're building tauthon incorrectly. (It's the interpreter, not a python package, so has a different build mechanism). Instead do:

```
$ brew install openssl xz
$ CPPFLAGS="-I$(brew --prefix openssl)/include" LDFLAGS="-L$(brew --prefix openssl)/lib" MACOSX_DEPLOYMENT_TARGET=10.6 ./configure
$ make
```

(This is also the way to build the ordinary CPython interpreter).

**Comment by torgil** [comment]
After getting `ranlib: Cannot find plugin 'liblto_plugin.so'` and tried numerous compilers with various errors and options I finally figured out to do `rm /usr/local/bin/ranlib` (mismatching binaries in my toolchain) and got it working with your config.

Binary is now "tauthon.exe" and your examples work. Awesome! Thanks!

I'll dig in to the world of ruby and try to get a homebrew package working. If someone with homebrew knowledge (maybe a former Python maintainer), please jump ahead and don't wait for me.

**Comment by naftaliharris** [comment]
Excellent, thank you! :-)

Let me know if/when you need me to cut a release, (i.e. tar up the project and peg a version number to it).

**Comment by proteasome** [comment]
i tend to avoid brew and use conda/pip.   i didn't see an easy way to use conda, so i just dug into the tauthon-master/Makefile and saw this
"""
#       ./configure
#       make
#       make test
#       make install
# If you have a previous version of Python installed that you don't
# want to overwrite, you can use "make altinstall" instead of "make
# install". 
"""

everything seems to be working fine using **make altinstall**,
**except numpy**

**Comment by torgil** [comment]
A strategic question before I start:
Are we aiming for python2 replacement here (eg link /usr/local/bin/python -> /usr/local/Cellar/tauthon/...  ) or should we stay with tauthon and let those who want this do the link?
I could go either way as I probably want to get accustomed to "tauthon" anyway.

If we stay with "tauthon", what naming should we use for "idle", "pip" etc?

**Comment by torgil** [comment]
proteasome: it'll be very hard to replace python itself with pip. You could lobby on Continuum to move to tauthon for Python2. That'd be awesome for windows users!

**Comment by naftaliharris** [comment]
> Are we aiming for python2 replacement here (eg link /usr/local/bin/python -> /usr/local/Cellar/tauthon/... ) or should we stay with tauthon and let those who want this do the link?

tauthon should be a new executable, (/usr/local/bin/python should not be changed to link to it). Not sure what to do about pip, though. Ideas?

**Comment by proteasome** [comment]
when building on OSX,  i'm surprised to get tauthon.exe instead of just tauthon, especially since i don't have any python.exe executable files in my usual python builds, just python.  i'm .exe is windows only, or am i missing something here?  (i'm NOT using brew, so i may have mangled something).   certainly the tuthon.exe works(mostly). so it 's not a showstopper

**Comment by torgil** [comment]
I looked at Ubuntu handling of idle today and maybe there isn't a big issue here. idle is installed to idle-python2.7 and idle-python3.5
we could just install it to idle-tauthon2.8
There were no symlinks from idle3 or idle but they should have been idle -> idle-python2.7 and idle3 -> python3.5. Then every user can use update-alternatives to which idle they want.

Maybe we should have a convenience-link to latest tauthon but it's not a urgent question I think.

**Comment by naftaliharris** [comment]
> when building on OSX, i'm surprised to get tauthon.exe instead of just tauthon, especially since i don't have any python.exe executable files in my usual python builds, just python.

Yeah, I'm not sure why this is, but CPython also gives the OSX executable a ".exe" extension when you build it. Although if you install it with "make install", I believe the ".exe" extension should be dropped in the installed binary?

**Comment by proteasome** [comment]
yep.  it was an artifact of using only "make altinstall". which only creates a local tauthon.exe and no tauthon.

however, using "make install" steps on my python2 (2.7.13):

"""
$ which -a tauthon.exe
$
$  ls -l `which -a tauthon`
lrwxr-xr-x  1 enzyme  admin  7 Feb 27 11:00 /usr/local/bin/tauthon -> python2
$ ls -l /usr/local/bin/python2
lrwxr-xr-x  1 enzyme  admin  9 Feb 27 11:00 /usr/local/bin/python2 -> python2.8
"""
i didn;t notice at first since i'm using anaconda, however, i'd rather not have it stepped on
"""
└─╼ which -a python2
/Users/enzyme/anaconda/bin/python2
/usr/local/bin/python2
"""

this will probably be fixed when the the other python refs are changed to tauthon.

not sure if "make altinstall" for vanilla python create only .exe

**Comment by n3h3m** [comment]
Where are we with this? I would like to see `tauthon` to be installed Homebrew at the earliest :)
